### PR TITLE
Add the pilz/LINI trajectory generator

### PR DESCRIPTION
**Pull request by galou**
### Description

Add the LINI trajectory generator that interpolates the seed between the initial and final pose rather than taking the solution of the IK of the previous point as seed.

### Checklist
- [x] **Required by CI**: Code is auto formatted using [clang-format](http://moveit.ros.org/documentation/contributing/code)
- [ ] Extend the tutorials / documentation [reference](http://moveit.ros.org/documentation/contributing/)
- [ ] Document API changes relevant to the user in the [MIGRATION.md](https://github.com/ros-planning/moveit/blob/master/MIGRATION.md) notes
- [ ] Create tests, which fail without this PR [reference](https://ros-planning.github.io/moveit_tutorials/doc/tests/tests_tutorial.html)
- [ ] Include a screenshot if changing a GUI
- [ ] While waiting for someone to review your request, please help review [another open pull request](https://github.com/ros-planning/moveit/pulls) to support the maintainers

[//]: # "You can expect a response from a maintainer within 7 days. If you haven't heard anything by then, feel free to ping the thread. Thank you!"

### CODE REVIEW

**Comment by jmarsik** [comment]
Definitely needs a better title :)

**Comment by galou** [comment]
I don't intend to publish this upstream but changed the title though.

**Comment by jmarsik** [comment]
Doesn't matter, we still need the best history possible. One that we can understand after a few years. Believe me ...

The other thing is combining other stuff into the PR that should not be there (here for example this deletion of log message with `waitForExecution` and maybe a few others). Also a lot of copied code and I'm not able to quickly determine if there was a way to do it differently for at least part of the methods (add functionality and some parameter to control it, then add overload with the original signature, for example), or not.

Wouldn't it be better to do this as a separate package with just this LINI trajectory generator, as we discussed quickly on the call about 7th axis position optimalization? If it's just an experiment or a temporary solution, then it's another reason to think about such solution.

What do you think?

**Comment by galou** [comment]
Doing it as a separate package may be the best option. I'll have a look whether this is possible.

**Comment by jmarsik** [comment]
What should I do with this pull request? @galou @dolejjir7
LINI planner is now implemented as a separate plugin in our repository or it should be here?

**Comment by galou** [comment]
Integrated in our repository, closing this PR.

**Pull request closed without merging**
